# language: php
build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
    coverage:
      tests:
        override:
          - command: composer run tests-with-coverage
            coverage:
              file: coverage.xml
              format: clover

filter:
  excluded_paths:
    - 'tests/*'
